### ISSUE TITLE
When English UI?

### ISSUE THREAD

**Issue by Redstonerayy** [Benbinbin/TagDown#2]
When ist there a translation of the UI into english available, and i dont just mean the tooltips?

**Comment by Benbinbin** [comment]
maybe the next version, now I'm waiting for [a new api](https://bugs.chromium.org/p/chromium/issues/detail?id=104102) from Chrome to support the favicon in manifest v3,  so that all bookmark icons can show correctly.
And then this extension may be avaliable in Chrome Web Store or Microsoft Edge Extensions.

**Comment by Redstonerayy** [comment]
nice to hear that.
